let date = {
    seoua: "Сервіс активної реклами та реального заробітку.     Лідер на ринку у своїй сфері! Багаторічний досвід! Широкий спектр послуг з реклами та заробітку в інтернеті!",
    wmzonaua: "Wmzona - інтернет-сервіс, що дозволяє заробляти гроші в Інтернеті виконуючи завдання. Також можна заробляти на коментарях в інстаграмі і тіктоці.",
    coinpayuua: "Coinpayu — це безкоштовна платформа винагород, на якій ви можете заробляти криптовалюту, переглядаючи рекламу або роблячи пропозиції.Для виведення коштів потрібно faucetpay кошелек. Його можна створити тут.",
    adBTCua: "Цей сайт дозволяє заробити в інтернеті, не докладаючи великих зусиль. Це краще, ніж кран, це не майнінг, просто заробіток онлайн за перегляд веб-сторінок, в основному сайтів про заробіток в інтернеті. Інтернет-реклама розвивається, і тепер ви маєте право отримувати гроші за це! ",
    surfebeua: "Це рекламна платформа, яка забезпечить вам швидкий і дешевий потік потенційних клієнтів на веб-сайт. Банерна або текстова реклама. Спливаючі вікна.",
    seoru: "Сервис активной рекламы и реального заработка. Лидер на рынке в своей сфере! Многолетний опыт! Широкий спектр услуг по рекламе и заработку в интернете!",
    surfeberu: "Это рекламная платформа, которая обеспечит вам быстрый и дешевый поток потенциальных клиентов на сайте. Баннерная или текстовая реклама. Всплывающие окна.",
    wmzonaru: "Wmzona – интернет-сервис, позволяющий зарабатывать деньги в Интернете выполняя задания. Также можно зарабатывать на комментариях в инстаграмме и тектоке.",
    adBTCru: "Этот сайт позволяет заработать в интернете, не прилагая огромных усилий. Это лучше, чем кран, это не майнинг, просто заработок онлайн за просмотр веб-страниц, в основном сайтов о заработке в интернете.Интернет-реклама развивается, и теперь вы имеете право получать деньги за это! ",
    coinpayurus: "Coinpayu – это бесплатная платформа вознаграждений, на которой вы можете зарабатывать криптовалюту, просматривая рекламу или делая предложения. Для вывода средств требуется faucetpay кошелек.",
    seous: "Service of active advertising and real earnings. Market leader in its field! Many years of experience! A wide range of services for advertising and earnings on the Internet!",
    wmzonaus: "Wmzona is an online service that allows you to make money online by completing tasks. You can also make money on Instagram and Ticket Comments.",
    coinpayuus: "Coinpayu is a free reward platform where you can earn cryptocurrency by viewing advertisements or making offers. You need a faucetpay wallet to withdraw funds. You can create one here.",
    adBTCus: "This site allows you to make money online without much effort. It's better than a tap, it's not mining, just make money online by browsing the web, mostly sites about making money online. Online advertising is evolving, and now you have the right get paid for it!",
    surfebeus: "It's an advertising platform that will provide you with a fast and cheap flow of potential customers to a website. Banner or text advertising. Pop-ups.",
    ru:"Ссылка на другой кран. Нажмите на картинку чтобы перейти по ссылке",
    ua:"Посилання на інший кран. Натисніть на картинку, щоб перейти за посиланням",
    us:"Link to another tap. Click on the image to follow the link to another tap. Click on the image to follow the link",
};
